// Mocks generated by Mockito 5.4.6 from annotations
// in astronomy_picture/test/data/datasource/search/search_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astronomy_picture/core/device_info.dart' as _i6;
import 'package:astronomy_picture/data/repositories/core/translator_service.dart'
    as _i3;
import 'package:google_mlkit_translation/google_mlkit_translation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOnDeviceTranslator_0 extends _i1.SmartFake
    implements _i2.OnDeviceTranslator {
  _FakeOnDeviceTranslator_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnDeviceTranslatorModelManager_1 extends _i1.SmartFake
    implements _i2.OnDeviceTranslatorModelManager {
  _FakeOnDeviceTranslatorModelManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeTranslationService_2 extends _i1.SmartFake
    implements _i3.TranslationService {
  _FakeTranslationService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationService extends _i1.Mock
    implements _i3.TranslationService {
  @override
  _i2.OnDeviceTranslator get translator =>
      (super.noSuchMethod(
            Invocation.getter(#translator),
            returnValue: _FakeOnDeviceTranslator_0(
              this,
              Invocation.getter(#translator),
            ),
            returnValueForMissingStub: _FakeOnDeviceTranslator_0(
              this,
              Invocation.getter(#translator),
            ),
          )
          as _i2.OnDeviceTranslator);

  @override
  _i2.OnDeviceTranslatorModelManager get modelManager =>
      (super.noSuchMethod(
            Invocation.getter(#modelManager),
            returnValue: _FakeOnDeviceTranslatorModelManager_1(
              this,
              Invocation.getter(#modelManager),
            ),
            returnValueForMissingStub: _FakeOnDeviceTranslatorModelManager_1(
              this,
              Invocation.getter(#modelManager),
            ),
          )
          as _i2.OnDeviceTranslatorModelManager);

  @override
  set translator(_i2.OnDeviceTranslator? value) => super.noSuchMethod(
    Invocation.setter(#translator, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> translate(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [text]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#translate, [text]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#translate, [text]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DeviceInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfo extends _i1.Mock implements _i6.DeviceInfo {
  @override
  _i3.TranslationService get translator =>
      (super.noSuchMethod(
            Invocation.getter(#translator),
            returnValue: _FakeTranslationService_2(
              this,
              Invocation.getter(#translator),
            ),
            returnValueForMissingStub: _FakeTranslationService_2(
              this,
              Invocation.getter(#translator),
            ),
          )
          as _i3.TranslationService);

  @override
  bool get deviceIsEnglish =>
      (super.noSuchMethod(
            Invocation.getter(#deviceIsEnglish),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<String> translateIfNeeded(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#translateIfNeeded, [text]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#translateIfNeeded, [text]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#translateIfNeeded, [text]),
              ),
            ),
          )
          as _i4.Future<String>);
}
